#!/usr/bin/php
<?php
error_reporting(E_ERROR | E_PARSE);
if (php_sapi_name() !== 'cli') { exit; }

require __DIR__ . '/vendor/autoload.php';

use Advent\Logger;

spl_autoload_register(function ($class) {
    $file = "lib/$className.php";
    if (file_exists($file)) {
        include $file;
    } else {
        throw new Error("Unable to load class, $class does not exist");
    }
});

$day = "Advent\Day00";
if (isset($argv[1])) {
    $day = "Advent\Day" . $argv[1];
}

Logger::log("$day Start");
$ts = microtime(true);

$test = "";
if ($argv[2] === "test") { $test = "-test"; }
$lines = file("data/day{$argv[1]}$test.txt", FILE_IGNORE_NEW_LINES);
$runner = new $day();
$runner->run($lines);

$te = microtime(true);
$t = round($te - $ts, 3);
Logger::log("$day ran for {$t}s");
